# Generated by Django 5.0.3 on 2024-03-29 17:15

import django.utils.timezone
from django.db import migrations, models

import geeohdotnet.models
import geeohdotnet.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=geeohdotnet.models._gen_pk,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=30, unique=True)),
                ("description", models.CharField(max_length=60)),
                (
                    "thumb",
                    models.FileField(
                        storage=geeohdotnet.storage.OverwriteStorage,
                        upload_to=geeohdotnet.models._thumb_loc,
                    ),
                ),
                (
                    "banner",
                    models.FileField(
                        storage=geeohdotnet.storage.OverwriteStorage,
                        upload_to=geeohdotnet.models._banner_loc,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Motto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motto", models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
