# Generated by Django 5.0.3 on 2024-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=30, unique=True)),
                ("description", models.CharField(max_length=60)),
                ("content", models.TextField()),
            ],
        ),
    ]
